### ISSUE TITLE
Potential conflict between object store names and server methods

### ISSUE THREAD

**Issue by brettz9** [aaronpowell/db.js#136]
If the user has an object store whose name is equal to one of the server methods (e.g., `count`, `query`, etc.), the method will be overwritten when calling `open()` (i.e., when iterating `objectStoreNames`).

My thought was to:

1. Allow a boolean `noServerMethods` option to be passed to `open()` which, when true, would avoid adding the methods on the server object, allowing the user to avoid adding extra functions in memory and in case they actually need an object store using one of our method names.
2. Throw an error if a duplicate is found when `noServerMethods` is missing or false.

**Comment by brettz9** [comment]
I've written some code for this approach already, so let me know if you want a PR or have an idea for a different approach. I don't think it would be good to auto-prefix store names to avoid conflicts, however, as that would make your library more as a framework locking people in, and I think it is better to remain as just a transparent wrapper to the IndexedDB functionality.

**Comment by aaronpowell** [comment]
To be honest I'd see it's not an overly common situation, are you likely to name an object store `query`? seems like it'd be confusing a usage. But then again I can't dictate db design...

An alternate would be to just set the prototype of the function (let's use `query` as an example) since none of the _members_ of `Server` are anything but functions you can do `db.query.count()` which is the same as `db.query('query').count()`.

Otherwise the property and raising an error makes the most sense

**Comment by brettz9** [comment]
I think it'd be preferable to avoid requiring workarounds by the user. If the full behavior can't be expressed, I think it'd be better to just throw an error and allow the property if that's ok.

**Comment by brettz9** [comment]
Are you open to a PR with the general approach taken in https://github.com/brettz9/db.js/commit/61fc15331f45fa8aebf7639addf7f21ece20a5e1 and https://github.com/brettz9/db.js/commit/f8eff56de965d4f470492488a72b8908e6bb2286 (though of course adapted to your current master and utilizing ES6 where suitable)?

**Comment by brettz9** [comment]
Thanks for the merge!
